[fastapi]
fastapi-server ansible_host=REPLACE_WITH_FASTAPI_PUBLIC_IP

[nexus]
nexus-server ansible_host=REPLACE_WITH_NEXUS_PUBLIC_IP

[monitoring]
monitoring-server ansible_host=REPLACE_WITH_MONITORING_PUBLIC_IP

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/fastapi-realworld-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
