---
- name: Create Grafana data directory
  ansible.builtin.file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: "0755"

- name: Pull Grafana image
  community.docker.docker_image:
    name: "{{ grafana_image }}"
    tag: "{{ grafana_version }}"
    source: pull

- name: Run Grafana
  community.docker.docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}:{{ grafana_version }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ grafana_port }}:3000"
    volumes:
      - "{{ grafana_data_dir }}:/var/lib/grafana"